languageCode = "en-us"
title = "Grew"
baseURL = "https://grew.fr/"
enableEmoji=true

theme = "hyde"

[params]
  themeColor = "theme-base-0d"
  layoutReverse = true

[markup.goldmark.renderer]
  unsafe= true

[module]
  [[module.mounts]]
    source = 'content'
    target = 'content'
